# NumPy

In [ ]:
import numpy as np

In [6]:
scores = [90, 70, 60]

In [7]:
np.mean(scores)

73.33333333333333

In [8]:
np.sum(scores)

220

In [9]:
np.std(scores)

12.472191289246473

# Arange, Linspace & Logspace

In [12]:
numbers = np.arange(0, 11, 2)
numbers

array([ 0,  2,  4,  6,  8, 10])

In [13]:
numbers.sum()

30

In [14]:
numbers = np.linspace(0, 10, 5)
numbers

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
numbers = np.logspace(-3, 3, 7)
numbers

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

#  Random

In [19]:
np.random.rand(3, 2)

array([[0.3077662 , 0.40693044],
       [0.86609681, 0.15790726],
       [0.68423774, 0.61636793]])

# Controlled Randomness

In [22]:
state = np.random.RandomState(1)
state.randint(1, 10, 5)

array([6, 9, 6, 1, 1])